version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Lerna bootstrap
          command: yarn bootstrap

      - run:
          name: Run tests
          command: yarn test --runInBand --no-cache --coverage --ci --all --bail

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish-packages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '5d:4d:1f:4d:bd:06:3f:00:d6:4c:68:8d:4e:90:85:2d'
      - run:
          name: Git setup
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            git config --global push.default matching
      - run:
          name: NPM setup
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Build packages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              yarn build        
            fi
            git status
            git add .size-snapshot.json
            git commit --amend --no-edit
            git status
            git log HEAD..origin/master
      - run:
          name: Bump versions
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              yarn lerna:version         
            fi
            git status
      - run:
          name: Publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              yarn lerna:publish         
            fi

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish-packages:
          requires:
            - test
