version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Lerna bootstrap
          command: yarn bootstrap

      - run:
          name: Run tests
          command: yarn test --runInBand --no-cache --coverage --ci --all --bail

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish-packages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '5d:4d:1f:4d:bd:06:3f:00:d6:4c:68:8d:4e:90:85:2d'
      - run:
          name: Git setup
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            git config --global push.default matching
      - run:
          name: Bump versions
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              npx lerna version
            fi
      - run:
          name: Build packages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              yarn build     
              if [ -n "$(git status --porcelain)" ]; then   
                git add .size-snapshot.json
                git commit -m "chore(build): update size-snapshot.json [ci skip]"
                git push
              else
                echo "no changes";
              fi
            fi
      - run:
          name: Authenticate with NPM egistry
          command: echo -e "@form-foundations:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              npx lerna publish from-package      
            fi
  deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: Build Docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
              yarn docs:build
            fi
      - run:
          name: Deploy Docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then 
               now --public --token=$NOW_TOKEN && now alias --token=$NOW_TOKEN     
            fi
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish-packages:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-docs:
          requires:
            - test
          filters:
            branches:
              only: master
