const ERROR_CODES = {
  CLEAN_UP_ERROR: 'CLEAN_UP_ERROR',
  BABEL_PARSE_ERROR: 'BABEL_PARSE_ERROR',
  STATIC_ANALYSIS_ERROR: 'STATIC_ANALYSIS_ERROR',
  TS_DECLARATION_ERROR: 'TS_DECLARATION_ERROR'
};

exports.ERROR_CODES = ERROR_CODES;
